defmodule Aurora.Uix.Test.Web.ManualResourceTest do
  use Aurora.Uix.Test.Web, :aurora_uix_for_test
  use Aurora.Uix.Test.Web.UICase, :phoenix_case

  @auix_resource_metadata %{
    product: %Aurora.Uix.Resource{
      name: :product,
      schema: Aurora.Uix.Test.Inventory.Product,
      context: Aurora.Uix.Test.Inventory,
      opts: [],
      fields: %{
        id: %Aurora.Uix.Field{
          key: :id,
          type: :binary_id,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "id",
          label: "Id",
          placeholder: "Id",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-id-8",
          hidden: false,
          readonly: false,
          required: false,
          disabled: true,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        inactive: %Aurora.Uix.Field{
          key: :inactive,
          type: :boolean,
          html_type: :checkbox,
          renderer: nil,
          resource: :product,
          name: "inactive",
          label: "Inactive",
          placeholder: "Inactive",
          length: 5,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-inactive-29",
          hidden: false,
          readonly: false,
          required: false,
          disabled: true,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        name: %Aurora.Uix.Field{
          key: :name,
          type: :string,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "name",
          label: "Name",
          placeholder: "Name",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-name-10",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        status: %Aurora.Uix.Field{
          key: :status,
          type: :string,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "status",
          label: "Status",
          placeholder: "Status",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-status-27",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        length: %Aurora.Uix.Field{
          key: :length,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "length",
          label: "Length",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-length-22",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        description: %Aurora.Uix.Field{
          key: :description,
          type: :string,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "description",
          label: "Description",
          placeholder: "Description",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-description-11",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        reference: %Aurora.Uix.Field{
          key: :reference,
          type: :string,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "reference",
          label: "Reference",
          placeholder: "Reference",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-reference-9",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        image: %Aurora.Uix.Field{
          key: :image,
          type: :binary,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "image",
          label: "Image",
          placeholder: "Image",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-image-25",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        width: %Aurora.Uix.Field{
          key: :width,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "width",
          label: "Width",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-width-23",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        deleted: %Aurora.Uix.Field{
          key: :deleted,
          type: :boolean,
          html_type: :checkbox,
          renderer: nil,
          resource: :product,
          name: "deleted",
          label: "Deleted",
          placeholder: "Deleted",
          length: 5,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-deleted-28",
          hidden: false,
          readonly: false,
          required: false,
          disabled: true,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        inserted_at: %Aurora.Uix.Field{
          key: :inserted_at,
          type: :utc_datetime,
          html_type: :"datetime-local",
          renderer: nil,
          resource: :product,
          name: "inserted_at",
          label: "Inserted at",
          placeholder: "yyyy/MM/dd HH:mm:ss",
          length: 20,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-inserted_at-31",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: true,
          filterable?: true,
          data: %{}
        },
        updated_at: %Aurora.Uix.Field{
          key: :updated_at,
          type: :utc_datetime,
          html_type: :"datetime-local",
          renderer: nil,
          resource: :product,
          name: "updated_at",
          label: "Updated at",
          placeholder: "yyyy/MM/dd HH:mm:ss",
          length: 20,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-updated_at-32",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: true,
          filterable?: true,
          data: %{}
        },
        product_transactions: %Aurora.Uix.Field{
          key: :product_transactions,
          type: :one_to_many_association,
          html_type: :one_to_many_association,
          renderer: nil,
          resource: :product,
          name: "product_transactions",
          label: "",
          placeholder: "",
          length: 0,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-product_transactions-34",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: false,
          data: %{
            resource: :product_transaction,
            related: Aurora.Uix.Test.Inventory.ProductTransaction,
            related_key: :product_id,
            owner_key: :id
          }
        },
        product_location: %Aurora.Uix.Field{
          key: :product_location,
          type: :many_to_one_association,
          html_type: :many_to_one_association,
          renderer: nil,
          resource: :product,
          name: "product_location",
          label: "",
          placeholder: "",
          length: 0,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-product_location-35",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: false,
          data: %{
            resource: nil,
            related: Aurora.Uix.Test.Inventory.ProductLocation,
            related_key: :id,
            owner_key: :product_location_id
          }
        },
        product_location_id: %Aurora.Uix.Field{
          key: :product_location_id,
          type: :binary_id,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "product_location_id",
          label: "Product location id",
          placeholder: "Product_location_id",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-product_location_id-30",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        quantity_at_hand: %Aurora.Uix.Field{
          key: :quantity_at_hand,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "quantity_at_hand",
          label: "Quantity at hand",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-quantity_at_hand-12",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        quantity_initial: %Aurora.Uix.Field{
          key: :quantity_initial,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "quantity_initial",
          label: "Quantity initial",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-quantity_initial-13",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        quantity_entries: %Aurora.Uix.Field{
          key: :quantity_entries,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "quantity_entries",
          label: "Quantity entries",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-quantity_entries-14",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        quantity_exits: %Aurora.Uix.Field{
          key: :quantity_exits,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "quantity_exits",
          label: "Quantity exits",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-quantity_exits-15",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        cost: %Aurora.Uix.Field{
          key: :cost,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "cost",
          label: "Cost",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-cost-16",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        msrp: %Aurora.Uix.Field{
          key: :msrp,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "msrp",
          label: "Msrp",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-msrp-17",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        rrp: %Aurora.Uix.Field{
          key: :rrp,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "rrp",
          label: "Rrp",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-rrp-18",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        list_price: %Aurora.Uix.Field{
          key: :list_price,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "list_price",
          label: "List price",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-list_price-19",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        discounted_price: %Aurora.Uix.Field{
          key: :discounted_price,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "discounted_price",
          label: "Discounted price",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-discounted_price-20",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        weight: %Aurora.Uix.Field{
          key: :weight,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "weight",
          label: "Weight",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-weight-21",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        height: %Aurora.Uix.Field{
          key: :height,
          type: :decimal,
          html_type: :number,
          renderer: nil,
          resource: :product,
          name: "height",
          label: "Height",
          placeholder: "0",
          length: 12,
          precision: 10,
          scale: 2,
          html_id: "auix-field-product-height-24",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        },
        thumbnail: %Aurora.Uix.Field{
          key: :thumbnail,
          type: :binary,
          html_type: :text,
          renderer: nil,
          resource: :product,
          name: "thumbnail",
          label: "Thumbnail",
          placeholder: "Thumbnail",
          length: 255,
          precision: 0,
          scale: 0,
          html_id: "auix-field-product-thumbnail-26",
          hidden: false,
          readonly: false,
          required: false,
          disabled: false,
          omitted: false,
          filterable?: true,
          data: %{}
        }
      },
      fields_order: [
        :id,
        :reference,
        :name,
        :description,
        :quantity_at_hand,
        :quantity_initial,
        :quantity_entries,
        :quantity_exits,
        :cost,
        :msrp,
        :rrp,
        :list_price,
        :discounted_price,
        :weight,
        :length,
        :width,
        :height,
        :image,
        :thumbnail,
        :status,
        :deleted,
        :inactive,
        :product_location_id,
        :product_transactions,
        :product_location
      ],
      inner_elements: []
    }
  }

  # When you define a link in a test, add a line to test/support/app_web/router.exs
  # See section `Including cases_live tests in the test server` in the README.md file.
  auix_create_ui link_prefix: "manual-resource-" do
    edit_layout :product, [] do
      inline([:reference, :name, :description])
      inline([:quantity_at_hand, :quantity_initial])
      inline([:list_price, :rrp])
    end
  end

  test "Test UI default with schema, context, basic layout", %{conn: conn} do
    {:ok, view, html} = live(conn, "/manual-resource-products")
    assert html =~ "Listing Products"
    assert html =~ "New Product"

    assert view
           |> element("a[name='auix-new-product']")
           |> render_click() =~ "New Product"
  end

  test "Test CREATE new, context, basic layout", %{conn: conn} do
    delete_all_sample_data()
    {:ok, view, html} = live(conn, "/manual-resource-products/new")

    assert html =~ "New Product"

    assert view
           |> form("#auix-product-form",
             product: %{reference: "test-first", name: "This is the first test"}
           )
           |> render_change() =~ "can&#39;t be blank"

    view
    |> form("#auix-product-form",
      product: %{quantity_initial: 11}
    )
    |> render_submit()

    {:ok, _view, new_html} = live(conn, "/manual-resource-products")

    assert new_html =~ "Listing Products"
    assert new_html =~ "test-first"
  end
end
