defmodule IconGenerator do

  @icons_root_dir "deps/heroicons/optimized/"
  @output_file "assets/css/icons.css"

  def run do
    :inets.start()
    # Jason is a dependency of Phoenix, so it should be available.
    # If not, add {:jason, "~> 1.2"} to mix.exs
    Application.ensure_all_started(:jason)

    tasks =
      for {suffix, directory} <- icon_sets() do
        Task.async(fn ->
          IO.puts("Fetching icon list for #{directory}...")
          read_and_process_icons(suffix, directory)
        end)
      end

      css_rules = Task.await_many(tasks, :infinity) |> List.flatten()

      File.write!(@output_file, "/* Generated by a script. Do not edit. */\n" <> Enum.join(css_rules, "\n"))

      IO.puts("\e[32mGenerated #{length(css_rules)} icon classes in #{@output_file}\e[0m")
  end

  defp icon_sets do
    [
      {"", "/24/outline"},
      {"-solid", "/24/solid"},
      {"-mini", "/20/solid"},
      {"-micro", "/16/solid"}
    ]
  end

  defp read_and_process_icons(suffix, directory) do
    icons_path = Path.join(@icons_root_dir, directory)
    icons_path
    |> File.ls!()
    |> Enum.map(&generate_css(&1, suffix, icons_path))
  end

  defp generate_css(file_name, suffix, icons_path) do
      content = icons_path |> Path.join(file_name) |> File.read!() |> String.replace("\n" , "")
      icon_name = Path.basename(file_name, ".svg") <> suffix

      """
        .hero-#{icon_name} {
          -webkit-mask: url('data:image/svg+xml,#{content}');
          mask: url('data:image/svg+xml,#{content}');
          mask-repeat: no-repeat;
          background-color: currentColor;
          vertical-align: middle;
          display: inline-block;
          width: #{icon_size(icon_name)};
          height: #{icon_size(icon_name)};
        }
      """
  end

  defp icon_size(name) do
    cond do
      String.ends_with?(name, "-mini") -> "1.25rem"
      String.ends_with?(name, "-micro") -> "1.0rem"
      true -> "1.5rem"
    end
  end
end

IconGenerator.run()
