defmodule Aurora.Uix.GettextBackend do
  @moduledoc """
  Default Gettext backend for Aurora UIX.

  Implements the three `Gettext.Backend` callbacks — `handle_missing_translation/5`,
  `handle_missing_plural_translation/7`, and `handle_missing_bindings/2` — and adds two
  optional behaviours controlled by compile-time configuration:

  - **Warning emission** — logs a `Logger.warning` for every missing translation so gaps are
    visible during development.
  - **POT file generation** — appends a stub entry to the matching `.pot` file the first time
    an `msgid` is encountered at runtime, keeping translation templates in sync with the UI
    without any manual editing.

  See the [Internationalization guide](guides/core/internationalization.md) for the full
  configuration reference and recommended development workflow.

  ## Compile-time configuration

  All options are read once at compile time via `Application.compile_env/2`:

  | Key | Type | Default | Description |
  |---|---|---|---|
  | `:gettext_pot_path` | `String.t() \\| nil` | `nil` | Directory where `.pot` files are written. No file I/O when `nil`. |
  | `:gettext_show_warnings?` | `boolean()` | `false` | Set to `true` to emit `Logger.warning` calls for missing translations. Warnings are suppressed by default. |

  ```elixir
  # config/dev.exs — recommended development settings
  config :aurora_uix,
    gettext_pot_path: "priv/gettext",
    gettext_show_warnings?: true
  ```

  ## Replacing this backend

  Pass a different module via the `:gettext_backend` application key or via the `:backend` option
  on `use Aurora.Uix.Gettext`:

  ```elixir
  config :aurora_uix, gettext_backend: MyApp.CustomGettextBackend
  ```

  See `Aurora.Uix.Gettext` for the backend resolution order.
  """
  use Gettext.Backend, otp_app: :aurora_uix

  @show_warnings? Application.compile_env(:aurora_uix, :gettext_show_warnings?, false)
  @pot_heading """
  # Generated by Aurora Uix
  """

  @impl true
  def handle_missing_translation(locale, domain, _msgctxt, msgid, _bindings) do
    if @show_warnings?,
      do: Logger.warning("Missing translation: #{locale}, #{domain}, #{msgid}")

    pot_path = Application.get_env(:aurora_uix, :gettext_pot_path)
    generate_pot_file(pot_path, domain, msgid)
    {:default, msgid}
  end

  @impl true
  def handle_missing_plural_translation(
        locale,
        domain,
        _msgctxt,
        msgid,
        msgid_plural,
        n,
        _bindings
      ) do
    if @show_warnings?,
      do: Logger.warning("Missing plural translation: #{locale}, #{domain}, #{msgid}")

    pot_path = Application.get_env(:aurora_uix, :gettext_pot_path)
    generate_pot_file(pot_path, domain, msgid, msgid_plural)
    {:default, if(n == 1, do: msgid, else: msgid_plural)}
  end

  @impl true
  def handle_missing_bindings(exception, incomplete) do
    if @show_warnings?, do: exception |> Exception.message() |> Logger.warning()
    incomplete
  end

  @spec generate_pot_file(binary() | nil, binary(), binary(), binary() | nil) ::
          :ok | {:error, term()}
  defp generate_pot_file(pot_path, domain, msgid, msgid_plural \\ nil)
  defp generate_pot_file(nil, _domain, _msgid, _msgid_plural), do: :ok

  defp generate_pot_file(pot_path, domain, msgid, msgid_plural) do
    path = Path.join(pot_path, "#{domain}.pot")

    with {:ok, _} <- maybe_create_file(path, File.exists?(path)),
         {:ok, lines} <- File.read(path),
         false <- String.contains?(lines, "msgid \"#{msgid}\"") do
      new_lines =
        if msgid_plural do
          """

          msgid "#{msgid}"
          msgid_plural "#{msgid_plural}"
          msgstr[0] ""
          msgstr[1] ""
          """
        else
          """

          msgid "#{msgid}"
          msgstr ""
          """
        end

      File.write(path, lines <> new_lines)
    end
  end

  @spec maybe_create_file(binary(), boolean()) :: {:ok, term()} | {:error, term()}
  defp maybe_create_file(path, false) do
    File.open(path, [:write, :utf8], fn file ->
      IO.write(file, @pot_heading)
    end)
  end

  defp maybe_create_file(_path, _exists), do: {:ok, ""}
end
