defmodule Aurora.Uix.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:author_profiles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:website, :text)
      add(:twitter_handle, :text)
      add(:years_active, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:authors,
          column: :id,
          name: "author_profiles_author_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:author_profiles, [:author_id],
             name: "author_profiles_unique_author_index"
           )
  end

  def down do
    drop(constraint(:author_profiles, "author_profiles_author_id_fkey"))

    drop_if_exists(
      unique_index(:author_profiles, [:author_id], name: "author_profiles_unique_author_index")
    )

    drop(table(:author_profiles))
  end
end
