defmodule Aurora.Uix.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:topics, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:slug, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:topics, [:slug], name: "topics_unique_slug_index")

    create table(:post_topics, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "post_topics_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :topic_id,
        references(:topics,
          column: :id,
          name: "post_topics_topic_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:post_topics, [:post_id, :topic_id],
             name: "post_topics_unique_post_topic_index"
           )
  end

  def down do
    drop(constraint(:post_topics, "post_topics_post_id_fkey"))

    drop(constraint(:post_topics, "post_topics_topic_id_fkey"))

    drop_if_exists(
      unique_index(:post_topics, [:post_id, :topic_id],
        name: "post_topics_unique_post_topic_index"
      )
    )

    drop(table(:post_topics))

    drop_if_exists(unique_index(:topics, [:slug], name: "topics_unique_slug_index"))

    drop(table(:topics))
  end
end
