defmodule Aurora.Uix.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text)
      add(:content, :text)
      add(:published_at, :utc_datetime)
      add(:status, :text, default: "draft")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:author_id, :uuid)
      add(:category_id, :uuid)
    end

    create table(:categories, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:description, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:authors, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:posts) do
      modify(
        :author_id,
        references(:authors,
          column: :id,
          name: "posts_author_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :category_id,
        references(:categories,
          column: :id,
          name: "posts_category_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:authors) do
      add(:name, :text)
      add(:email, :text)
      add(:bio, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:authors) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:bio)
      remove(:email)
      remove(:name)
    end

    drop(constraint(:posts, "posts_author_id_fkey"))

    drop(constraint(:posts, "posts_category_id_fkey"))

    alter table(:posts) do
      modify(:category_id, :uuid)
      modify(:author_id, :uuid)
    end

    drop(table(:authors))

    drop(table(:categories))

    drop(table(:posts))
  end
end
