defmodule Aurora.Uix.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:labels, {:array, :text})
    end
  end

  def down do
    alter table(:posts) do
      remove(:labels)
    end
  end
end
